### ISSUE TITLE
Deployment doesn't use latest vm branch(?)

### ISSUE THREAD

**Issue by LilyMakesThings** [Unsandboxed/scratch-gui#51]
Now look, you might think I'm stupid...

**Comment by David-Orangemoon** [comment]
Whoops

**Comment by LilyMakesThings** [comment]
> Whoops

Crazy because I just tested it locally and it works fine so I must have royally fucked up somewhere in github specifically for that to happen

**Comment by LilyMakesThings** [comment]
I've got no idea what's going on here, basically the deployment is using an older version of the vm and I cannot get it onto a newer one. Definitely just missing something obvious

**Comment by LilyMakesThings** [comment]
@GarboMuffin I don't expect you'll have any more of an idea of what's wrong here but I'll tag you anyway. I've used google, I've scrutinised every package and workflow file, I've redeployed, rebuilt, reinstalled every relevant dependency and repo, but scratch-gui is still deploying an old version of the vm.

**Comment by GarboMuffin** [comment]
The scratch-vm commit hash is defined here:

https://github.com/Unsandboxed/scratch-gui/blob/f9fc28f89abb8fc2249c4a165d05fddb9509b788/package-lock.json#L16470-L16472

76f22f09626e8003a60a4fcff4a409b40057f0b5 is https://github.com/Unsandboxed/scratch-vm/commit/76f22f09626e8003a60a4fcff4a409b40057f0b5

The fix is in scratch-gui do `npm update scratch-vm` and commit the changes. You can also do `npm update` which will try to update everything

**Comment by LilyMakesThings** [comment]
thank you, I had no idea

**Comment by LilyMakesThings** [comment]
lifesaver 💜

**Comment by AshimeeAlt** [comment]
yeah
